"openapi": "3.0.1"
"info":
  "title": "SQLite Database API"
  "version": "1.0.0"
  "description": "An API for interacting with an SQLite database."
"servers":
  - "url": "SERVEO_URL"
"paths":
  "/database/metadata":
    "get":
      "summary": "Get Database Metadata"
      "operationId": "getDatabaseMetadata"
      "responses":
        '200':
          "description": "Success"
          "content":
            "application/json":
              "schema":
                "type": "object"
                "properties":
                  "metadata":
                    "type": "object"
                    "description": "Metadata of the SQLite database"
      "security": []
  "/database/execute_query":
    "post":
      "summary": "Execute SQL Query"
      "operationId": "executeSQLQuery"  # Added operationId
      "requestBody":
        "required": true
        "content":
          "application/json":
            "schema":
              "type": "object"
              "properties":
                "query":
                  "type": "string"
                  "description": "SQL Query to execute"
      "responses":
        '200':
          "description": "Success"
          "content":
            "application/json":
              "schema":
                "type": "object"
                "properties":
                  "result":
                    "type": "array"
                    "description": "Result of the SQL query execution"
      "security": []
